In [17]:
import tensorflow as tf
#tf.__version__
from keras.models import Sequential
from keras.layers import Dense,Dropout
from keras.layers import Conv1D,GlobalAveragePooling1D,MaxPooling1D
import keras.metrics
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import sklearn
from sklearn.preprocessing import normalize
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score
from sklearn.metrics import precision_score
from sklearn.metrics import f1_score

In [12]:
#加载数据
train_data = pd.read_csv("hardware_train_set.csv")
test_data = pd.read_csv("hardware_test_set.csv")
#未处理的数据（有字符型数据）
train_data.head()

label  frame.len  ip.len  ip.flags.df  ip.flags.mf  ip.ttl  ip.proto  \
0      0         54      40            1            0      38         6   
1      0         58      44            1            0      36         6   
2      0         54      40            1            0     128         6   
3      0         54      40            1            0     128         6   
4      0         66      52            1            0     128         6   

   tcp.hdr_len  tcp.flags.ns  tcp.flags.ecn  ...  tcp.window_size_value  \
0         20.0           0.0            0.0  ...                26000.0   
1         24.0           0.0            0.0  ...                14600.0   
2         20.0           0.0            0.0  ...                  512.0   
3         20.0           0.0            0.0  ...                64240.0   
4         32.0           0.0            0.0  ...                64240.0   

   tcp.urgent_pointer  tcp.options.wscale.shift  tcp.options.mss_val  \
0                 0.0                       0.0                  0.0   
1                 0.0                       0.0               1300.0   
2                 0.0                       0.0                  0.0   
3                 0.0                       0.0                  0.0   
4                 0.0                       8.0               1460.0   

   tcp.options.timestamp.tsval  tcp.options.timestamp.tsecr  udp.length  \
0                          0.0                          0.0         0.0   
1                          0.0                          0.0         0.0   
2                          0.0                          0.0         0.0   
3                          0.0                          0.0         0.0   
4                          0.0                          0.0         0.0   

   udp.checksum  tcp.option_kind  _ws.col.Protocol  
0             0                0                 0  
1             0                2                 0  
2             0                0                 0  
3             0                0                 0  
4             0               12                 0  

[5 rows x 26 columns]

In [13]:

train_label = train_data['label']
test_label = test_data['label']

print(train_label)

train_set = np.array(train_data).astype(np.float32)
train_set = train_set[:,1:]

test_set = np.array(train_data).astype(np.float32)
test_set = test_set[:,1:]

print(train_set)

0           0
1           0
2           0
3           0
4           0
           ..
1101492    10
1101493    10
1101494    10
1101495    10
1101496    10
Name: label, Length: 1101497, dtype: int64
[[ 54.  40.   1. ...   0.   0.   0.]
 [ 58.  44.   1. ...   0.   2.   0.]
 [ 54.  40.   1. ...   0.   0.   0.]
 ...
 [ 54.  40.   1. ...   0.   0.   0.]
 [ 54.  40.   1. ...   0.   0.   0.]
 [162. 148.   1. ...   0.   0.   1.]]


In [18]:
# 5 特征归一化  用MLP的时候用，LSTM不用
min_max_scaler = normalize.MinMaxScaler()
train_set = min_max_scaler.fit_transform(train_set)
test_set = min_max_scaler.fit_transform(test_set)
print("x_train_GA.shape",train_set.shape)


# 6 标签转化为one-hot编码 
y_train = keras.utils.to_categorical(train_label, num_classes=23)
y_test = keras.utils.to_categorical(test_label, num_classes=23)

print("y_train.shape",y_train.shape)

AttributeError: 'function' object has no attribute 'MinMaxScaler'

In [ ]:
cnn_1D=Sequential()
cnn_1D.add(Conv1D(64,1,activation='relu',input_shape=(108,1)))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(MaxPooling1D(3))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(Conv1D(64,1,activation='relu'))
cnn_1D.add(GlobalAveragePooling1D())
cnn_1D.add(Dropout(0.5))
cnn_1D.add(Dense(11,activation='softmax'))
cnn_1D.compile(
    loss='sparse_categorical_crossentropy',
    optimizer='rmsprop',
    metrics=(['accuracy'])
)